# Generated by Django 4.2.1 on 2023-06-06 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_basketmodel_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketmodel',
            name='amount',
        ),
    ]
