# Generated by Django 4.2.1 on 2023-06-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0005_ordersmodel_adress_ordersmodel_messages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersmodel',
            name='messages',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
