# Generated by Django 4.2.1 on 2023-06-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0006_alter_ordersmodel_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersmodel',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
