# Generated by Django 4.2.1 on 2023-06-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0007_alter_ordersmodel_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersmodel',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
